nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      "@": "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
