name: "CI workflow production [Production]"
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    if: '${{ github.event.repository.full_name == github.repository }}'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: "Setting up node & yarn"
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: 14.17.3
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock
          architecture: "x64" # optional, x64 or x86. If not specified, x64 will be used by default

      - uses: c-hive/gha-yarn-cache@v2 # using cache

      - name: "Step #1: Installing dependencies"
        run: |
          yarn set version 3.1.1
          yarn install
          npm install -g firebase-tools

      - name: "Step #2: Configuring rinkeby env"
        run: yarn run ci:build:rinkeby

      - name: "Step #3: Deploying to the staging the latest valid code"
        uses: matter-labs/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZSYNC_DAPP_CHECKOUT_DEV }}'
          target: ยง
          projectId: zsync-dapp-checkout
          channelID: live
