name: "Deploy staging"
"on":
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: "Enable yarn cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache

      - name: "Setup node@16"
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: "Install dependencies"
        run: |
          yarn set version 3.1.1
          yarn install

      - name: "Lint"
        run: |
          yarn lint --max-warnings 0

      - name: "Deploy target: sepolia"
        run: yarn run ci:build:sepolia
        
      - name: "Setup node@18"
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZSYNC_DAPP_CHECKOUT_DEV }}"
          target: staging
          projectId: zsync-dapp-checkout
          channelID: live
