# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (12.16.2)
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'

      - name: Install Pacakges
        run: sh cli-dev.sh ci

      - name: Build Step
        env:
          CI: true
        run: yarn run ci:build:mainnet

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
